aviLunch:
    - שווארמה
    - המבורגר גורמה
    - אלגמוס
    - בהדונס
    - שניצל קומפני
    - עזורה
    - קפה בנגב
    - פיס אוף קייק לבונטין
    - קוויק קפה
    - נייצ'ר בויז
    - התימני
    - חומוס אליהו תל אביב
    - חומוס הכרם
    - בריא בר
    
restaurants:
    - שחרואד אוכל
    - JAPANIKA
    - פיצה פינו רמת אביב
    - בר דגים
    - גלידות נוה צדק
    - סופיצה
    - רולדין גבעתיים
    - קפה לנדוור- אושירה
    - רי באר בע"מ
    - ארקפה קניון הזהב
    - AREPA
    - איקאה- מסעדה
    - ארומה
    
bills:
    - ח-ן שרות סלקום
    - חב' חשמל דן
    - מי אביבים 2010
    - סופרגז לבית
    - עיריית תל אביב-יפו-ארנונה
    - Google Storage
    - פלאפון
    
groceries:
    - שופרסל אקספרס
    - שופרסל און ליין
    - יוחננוף
    - סופר זול שלהבת
    - סיטי מרקט טאואר
    
parm:
    - סופרפארם
    - סופר פארם
    - מדי-לינק פארם

car:
    - YELLOW
    - דלק מנטה
    - חניון
    - חניוני תל אביב
    - מפעלי דינמומטר לבדיקות
    - משרד התחבורה - רשיונות רכב
    - דלק גולדאור
    
insurance:
    - פניקס
    - כללית
    - הראל
    
weekend-pass-time:
    - כיף בפרדס
    - לב הכפר
    - ארץ הצבי
    