aviLunch:
    - שווארמה
    - המבורגר גורמה
    - אלגמוס
    - בהדונס
    - שניצל קומפני
    - עזורה
    - קפה בנגב
    - פיס אוף קייק לבונטין
    - קוויק קפה
    
restaurants:
    - שחרואד אוכל
    - JAPANIKA
    - פיצה פינו רמת אביב
    - בר דגים
    - גלידות נוה צדק
    
bills:
    - ח-ן שרות סלקום
    - חב' חשמל דן
    - מי אביבים 2010
    - סופרגז לבית
    - עיריית תל אביב-יפו-ארנונה
    - Google Storage
    
groceries:
    - שופרסל אקספרס
    - שופרסל און ליין
    - יוחננוף
    - סופר זול שלהבת
    
parm:
    - סופרפארם
    - סופר פארם